spring:
 application:
   name: helloservice
server:
     port: 8094
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
         defaultZone: http://localhost:8762/eureka
#         where registry is running
#          when the clients are going to register their details in the server so the path should be mentioned. 
  instance: 
    hostname: localhost     
